# Generated by Django 4.1.5 on 2023-01-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="hash",
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
