# Generated by Django 4.1.5 on 2023-01-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_alter_version_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fifotest",
            name="shortname",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
