name: Run tests

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  run-tests-runner:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fifoci/runner

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "fifoci/runner/pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Sync dependencies
      run: uv sync --locked --all-extras --dev

    - name: Check runner coding style
      run: uv run black --check .

  run-tests-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fifoci/frontend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "fifoci/frontend/pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Sync dependencies
      run: uv sync --locked --all-extras --dev

    - name: Check frontend coding style
      run: uv run black --check .

    - name: Run frontend unit tests
      run: uv run fifoci-frontend-manage test --noinput
