name: Run tests

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: snok/install-poetry@v1
      with:
        version: 1.3.0
        virtualenvs-create: true

    - name: Install dependencies
      run: |
        poetry -C fifoci/runner install --no-interaction --no-root
        poetry -C fifoci/frontend install --no-interaction --no-root

    - name: Check runner coding style
      run: poetry run -C fifoci/runner black --check fifoci/runner

    - name: Check frontend coding style
      run: poetry run -C fifoci/frontend black --check fifoci/frontend

    - name: Run frontend unit tests
      run: poetry run -C fifoci/frontend fifoci-frontend-manage test --noinput
